/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.{blade.php,js,jsx,ts,tsx}',
    ],
    theme: {
        extend: {
            colors: {
                'on-surface-variant': '#3c4a42',
                'on-secondary-fixed-variant': '#3f465c',
                'tertiary-container': '#94a4bd',
                'inverse-primary': '#4edea3',
                'tertiary': '#505f76',
                'primary': '#006c49',
                'accent': '#20b0f9',
                
                'secondary-fixed-dim': '#bec6e0',
                'on-secondary': '#ffffff',
                'primary-container': '#10b981',
                'inverse-surface': '#2d3133',
                'surface-container-lowest': '#ffffff',
                'secondary-fixed': '#dae2fd',
                'on-primary-container': '#00422b',
                'on-tertiary-fixed-variant': '#38485d',
                'outline-variant': '#bbcabf',
                'tertiary-fixed-dim': '#b7c8e1',
                'secondary': '#565e74',
                'outline': '#6c7a71',
                'surface': '#f7f9fb',
                'error': '#ba1a1a',
                'background': '#f7f9fb',
                'primary-fixed': '#6ffbbe',
                'on-primary': '#ffffff',
                'on-error': '#ffffff',
                'surface-container-high': '#e6e8ea',
                'primary-fixed-dim': '#4edea3',
                'on-tertiary': '#ffffff',
                'inverse-on-surface': '#eff1f3',
                'surface-container-low': '#f2f4f6',
                'on-background': '#191c1e',
                'surface-variant': '#e0e3e5',
                'on-tertiary-container': '#2a3a4f',
                'on-error-container': '#93000a',
                'on-tertiary-fixed': '#0b1c30',
                'on-secondary-container': '#5c647a',
                'surface-dim': '#d8dadc',
                'surface-bright': '#f7f9fb',
                'surface-container': '#eceef0',
                'on-primary-fixed-variant': '#005236',
                'tertiary-fixed': '#d3e4fe',
                'error-container': '#ffdad6',
                'secondary-container': '#dae2fd',
                'surface-container-highest': '#e0e3e5',
                'surface-tint': '#006c49',
                'on-secondary-fixed': '#131b2e',
                'on-surface': '#191c1e',
                'on-primary-fixed': '#002113',
               
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                'container-max': '1440px',
                'stack-md': '16px',
                'margin-mobile': '16px',
                'stack-lg': '24px',
                'gutter': '24px',
                'stack-sm': '8px',
                'margin-desktop': '32px',
            },
            fontFamily: {
                'headline-sm': ['Hanken Grotesk', 'sans-serif'],
                'headline-lg': ['Hanken Grotesk', 'sans-serif'],
                'body-md': ['Manrope', 'sans-serif'],
                'headline-md': ['Hanken Grotesk', 'sans-serif'],
                'body-lg': ['Manrope', 'sans-serif'],
                'label-md': ['Geist', 'sans-serif'],
            },
            fontSize: {
                'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
            },
        },
    },
    plugins: [],
}
